pipeline {
    agent any

    environment {
        cluster = 'vproprod'
        service = 'vproappProdsvc'
    }
    stages {
        stage('Deploy to prod ECS') {
            steps {
                withAWS(credentials: 'awscredid', region: 'us-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}